HOST_IP="192.168.3.19"
HOST_PORT="7890"
PROXY_URL="http://$HOST_IP:$HOST_PORT"
export ALL_PROXY=$PROXY_URL
export HTTP_PROXY=$PROXY_URL
export HTTPS_PROXY=$PROXY_URL

echo "ALL_PROXY: " $ALL_PROXY
echo "HTTP_PROXY: " $HTTP_PROXY
echo "HTTPS_PROXY: " $HTTPS_PROXY